export const REQUEST_CHECKUP_RESULT = 'REQUEST_CHECKUP_RESULT';
export const REQUEST_CHECKUP_RESULT_SUCCESS = 'REQUEST_CHECKUP_RESULT_SUCCESS';
export const REQUEST_CHECKUP_RESULT_ERROR = 'REQUEST_CHECKUP_RESULT_ERROR';
